#!/bin/bash

set -e

# Get these from env provided by docker hub build system
export VCS_REF="$SOURCE_COMMIT"
export VCS_BRANCH="$SOURCE_BRANCH"

export FORCE_PULL=true
export AUTO_PUSH=true

# Run the real build
source bin/build

# Tag the latest base as provided $IMAGE_NAME to make docker hub at ease
docker tag "$(get_target_image_name "base")" "$IMAGE_NAME"