#!/bin/bash

set -e

# Get these from env provided by docker hub build system
export VCS_REF="$SOURCE_COMMIT"
export VCS_BRANCH="$SOURCE_BRANCH"

export FORCE_PULL=true
export AUTO_PUSH=true

# Run the real build
source bin/build

# Tag the latest base as `:latest` to make docker hub at ease
export MCC_BASE_CURRENT="$(get_target_image_name "base")"
export TARGET_TAG="latest"
export MCC_BASE_LATEST="$(get_target_image_name "base")"
docker tag "$MCC_BASE_CURRENT" "$MCC_BASE_LATEST"